In [82]:
print ('hello')

hello


In [83]:
import numpy

In [84]:
# txt文件此时和代码在同一个文件夹下，直接用的文件名"world_alcohol.txt"来打开

In [85]:
world_alcohol = numpy.genfromtxt("world_alcohol.txt",delimiter=",",dtype=str,skip_header=1)
print(type(world_alcohol))# ndarray 结构

<class 'numpy.ndarray'>


In [86]:
print(world_alcohol)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [87]:
#打印hlep帮助文档，可以查看不同的函数

In [88]:
print(help(numpy.genfromtxt))

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings. The string

In [89]:
print(help(world_alcohol))

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [90]:
#numpy.array数组 take a list or lists as input;矩阵，二维数组用两个中括号

In [91]:
onevector=numpy.array([5,10,5,20]) 
matrix=numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(onevector)
print(matrix)

[ 5 10  5 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [92]:
#print .shape 用这个function查看数组 矩阵结构：行与列;若是1维数组则打印出来的是多少个元素；若是二维就是打印出几行几列

In [93]:
print(onevector.shape)

(4,)


In [94]:
print(matrix.shape)

(3, 3)


In [95]:
#numpy.array 里面的每个值都必须是相同的结构比如都是int/str/float, 通过ndarray中的.dtype来查看当前对象的类型

In [96]:
onevector.dtype

dtype('int64')

In [97]:
#取某个value数值：numpy和python一样，从0开始，所以[1,4]就是第二行第5个value

In [98]:
other=world_alcohol[1,4]
another=world_alcohol[2,2]
print (other)
print (another)

0.5
Cte d'Ivoire


In [99]:
#python中[]是左闭右开的区间，冒号:表示取某行/列的所有值，例如[:,1]表示取第二列的所有数，用切片形式，取两列则，[:,0:2],表示第1列和第2列

In [100]:
vector=numpy.array([5,10,15,20])
print(vector[0:3])

[ 5 10 15]


In [101]:
matrix=numpy.array([[5,10,15],
                    [20,25,30],
                    [35,40,45]])
print(matrix[:,0])

[ 5 20 35]


In [102]:
print(matrix[0:2,1:3])

[[10 15]
 [25 30]]


In [103]:
#比较值的大小compare the value to each element in the vector;如果等于10则会返回True；否则返回False；

In [104]:
vector == 10

array([False,  True, False, False])

In [105]:
matrix==25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [106]:
equal_to_ten = (vector==10)
print (equal_to_ten)

[False  True False False]


In [107]:
print(vector[equal_to_ten])#将布尔类型的值作为索引

[10]


In [108]:
second_column_25 = (matrix[:,1]==25)
print (second_column_25)

[False  True False]


In [109]:
print(matrix[second_column_25,:])

[[20 25 30]]


In [110]:
#comparisons with multiple conditions与或非

In [111]:
print(vector)

[ 5 10 15 20]


In [112]:
equal_to_tenandfive=(vector==5)&(vector==10)
print(equal_to_tenandfive)

[False False False False]


In [113]:
equal_to_tenandfive=(vector==5)|(vector==10)
print(equal_to_tenandfive)

[ True  True False False]


In [114]:
equal_to_tenandfive=(vector==5)|(vector==10)
print(vector[equal_to_tenandfive])

[ 5 10]


In [115]:
#convert the data type of an array with the ndarray.astype() method 强制转换数组数据类型

In [116]:
vector = numpy.array(["1","2","3"])
print (vector.dtype)
print (vector)

<U1
['1' '2' '3']


In [117]:
#将string类型转换为float类型。

In [118]:
vector=vector.astype(float)
print(vector.dtype)
print(vector)

float64
[1. 2. 3.]


In [119]:
#求最小值最大值

In [120]:
vector=numpy.array([5,10,15,20])
print(min(vector))
print(max(vector))

5
20


In [121]:
#矩阵求和，axis表示维度；the axis dictates which dimension we perform the operation on;
#1 means that we want to perform the operation on each row, and 0 means on each column
#在这里1表示对每一行进行求和，0表示对每一列进行求和操作

In [122]:
matrix=numpy.array([[5,10,15],
                    [20,25,30],
                    [35,40,45]])
print(matrix)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [123]:
matrix.sum(axis=0)

array([60, 75, 90])

In [124]:
matrix.sum(axis=1)

array([ 30,  75, 120])

In [125]:
#使用reshape函数把向量形式转换为矩阵形式,arange 范围

In [126]:
import numpy as np
print(np.arange(15))
a=np.arange(15).reshape(3,5)
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [127]:
a.shape

(3, 5)

In [128]:
#ndim 矩阵数组维度,例如这个二维矩阵

In [129]:
a.ndim

2

In [130]:
#dtype value的类型

In [131]:
a.dtype.name

'int64'

In [132]:
#the total number of elements of the array 数组一共有多少个元素

In [133]:
a.size

15

In [134]:
#矩阵的初始化

In [135]:
np.zeros((3,4))#未指定数据类型，为float

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
np.ones((2,3,4),dtype=np.int32)#定义数组值为int类型；三维矩阵

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [137]:
#构造序列

In [138]:
np.arange(10,30,5)#从10开始每个加5，最大不超过30

array([10, 15, 20, 25])

In [139]:
#随机函数

In [140]:
np.random.random((2,3))#首先进入random模块，再调用random函数

array([[0.83900805, 0.36570648, 0.32959728],
       [0.93567095, 0.7203714 , 0.31963792]])

In [141]:
#linspace 起始值是0 以2pi结束 平均取100个数

In [142]:
from numpy import pi
np.linspace(0,2*pi,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [143]:
np.sin(np.linspace(0,2*pi,100))

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [144]:
#不同的操作符运算

In [145]:
a= np.array([20,30,40,50])
b= np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [146]:
c=a-b
print(c)

[20 29 38 47]


In [147]:
c=c-1
c

array([19, 28, 37, 46])

In [148]:
b**2
print(b**2)
print(a<35)

[0 1 4 9]
[ True  True False False]


In [149]:
#矩阵🌟乘和矩阵点乘 *表示对应位置相乘/dot function表示矩阵点乘（1，1）第一行乘第一列相加

In [150]:
A = np.array([[1,1],[0,1]])
print(A)
B = np.array([[2,0],[3,4]])
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [151]:
print(A*B)

[[2 0]
 [0 4]]


In [154]:
import numpy
print(A.dot(B))

[[5 4]
 [3 4]]


In [155]:
print(np.dot(A,B))

[[5 4]
 [3 4]]


In [ ]:
# e的幂函数exp;平方根函数sqrt

In [156]:
B=np.arange(4)
B

array([0, 1, 2, 3])

In [157]:
print(np.exp(B))

[ 1.          2.71828183  7.3890561  20.08553692]


In [158]:
print(np.sqrt(B))

[0.         1.         1.41421356 1.73205081]


In [ ]:
#floor是向下取整操作，例如2.9 取2，2.5取2，2.1取2

In [162]:
a=np.floor(10*np.random.random((3,4)))
print(a)

[[2. 0. 7. 2.]
 [0. 9. 3. 7.]
 [1. 5. 2. 4.]]


In [ ]:
#ravel操作 将矩阵拉平，flatten the array

In [163]:
print(a.ravel())

[2. 0. 7. 2. 0. 9. 3. 7. 1. 5. 2. 4.]


In [167]:
print(a)

[[2. 0. 7. 2.]
 [0. 9. 3. 7.]
 [1. 5. 2. 4.]]


In [170]:
a.shape=(6,2)#指定shape为六行二列
a

array([[2., 0.],
       [7., 2.],
       [0., 9.],
       [3., 7.],
       [1., 5.],
       [2., 4.]])

In [ ]:
#矩阵的置换 行变成列 列变成行

In [171]:
print(a.T)

[[2. 7. 0. 3. 1. 2.]
 [0. 2. 9. 7. 5. 4.]]


In [ ]:
#reshaping operation:如果已知其中一个维度，另一个为-1表示 另一个维度可以被自动换算

In [172]:
a.reshape(3,-1)#例如这里就是3为已知的行数，使用-1，reshape函数会自动帮你计算为4列

array([[2., 0., 7., 2.],
       [0., 9., 3., 7.],
       [1., 5., 2., 4.]])

In [ ]:
#矩阵拼接hstack横着去拼接合并,vstack是纵向拼接

In [173]:
a=np.floor(10*np.random.random((2,2)))#随机数向下取整
b=np.floor(10*np.random.random((2,2)))
print(a)
print(b)

[[0. 9.]
 [3. 5.]]
[[0. 4.]
 [3. 0.]]


In [178]:
print(np.hstack((a,b)))

[[0. 9. 0. 4.]
 [3. 5. 3. 0.]]


In [180]:
print(np.vstack((a,b)))

[[0. 9.]
 [3. 5.]
 [0. 4.]
 [3. 0.]]


In [ ]:
#矩阵切割hsplit横着切割；指定切割加上一个元组，（3，4）表示在第三和第四列后面切一刀；vsplit纵向同理

In [186]:
a=np.floor(10*np.random.random((2,12)))
print(a)
print(np.hsplit(a,4))

[[7. 3. 7. 0. 9. 8. 9. 3. 1. 6. 8. 3.]
 [4. 2. 1. 8. 0. 8. 2. 0. 2. 3. 7. 2.]]
[array([[7., 3., 7.],
       [4., 2., 1.]]), array([[0., 9., 8.],
       [8., 0., 8.]]), array([[9., 3., 1.],
       [2., 0., 2.]]), array([[6., 8., 3.],
       [3., 7., 2.]])]


In [187]:
print(np.hsplit(a,(3,4)))

[array([[7., 3., 7.],
       [4., 2., 1.]]), array([[0.],
       [8.]]), array([[9., 8., 9., 3., 1., 6., 8., 3.],
       [0., 8., 2., 0., 2., 3., 7., 2.]])]


In [194]:
a=np.floor(10*np.random.random((12,2)))
print(a)

[[1. 6.]
 [8. 7.]
 [8. 4.]
 [6. 9.]
 [0. 6.]
 [8. 3.]
 [1. 4.]
 [1. 5.]
 [2. 9.]
 [6. 7.]
 [0. 4.]
 [9. 0.]]


In [195]:
print(np.vsplit(a,4))#平均切三份，每份四个

[array([[1., 6.],
       [8., 7.],
       [8., 4.]]), array([[6., 9.],
       [0., 6.],
       [8., 3.]]), array([[1., 4.],
       [1., 5.],
       [2., 9.]]), array([[6., 7.],
       [0., 4.],
       [9., 0.]])]


In [ ]:
#赋值

In [196]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [198]:
b=a
print(b is a)

True


In [199]:
print(id(a))

140350508425424


In [200]:
print(id(b))

140350508425424


In [ ]:
#view浅复制，a和c共用某一数值但并不指向同一事物

In [209]:
c=a.view()
print(c is a)
c.shape = 2,6
print(c)
print(a.shape)
c[0,4]=1234
print(a)
print(id(a))
print(id(c))#他们的身份证号不同

False
[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
(12,)
[   0    1    2    3 1234    5    6    7    8    9   10   11]
140350508425424
140350516601120


In [ ]:
#.copy深复制，a和c完全不是同一个事物

In [219]:
a.shape=(2,6)
d=a.copy()
print(a)
print(d is a)
d[0,0] = 10
print(d)

[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
False
[[  10    1    2    3 1234    5]
 [   6    7    8    9   10   11]]


In [ ]:
#求最大值及其对应在矩阵中的位置

In [220]:
data = np.sin(np.arange(20)).reshape(5,4)

In [241]:
print(data)
print(range(data.shape[1]))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
range(0, 4)


In [222]:
ind = data.argmax(axis=0)#索引index值寻找每一列最大值的位置

In [223]:
print(ind)#第一列的第三个数，第二列的第一个数，第三列的第四个数，第四列的第个数

[2 0 3 1]


In [236]:
data_max = data[ind,range(data.shape[1])]#将索引ind中的值传过来，找对应位置的value
print(data_max)

[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [ ]:
#行与列扩展

In [242]:
a=np.arange(0,40,10)
print(a)

[ 0 10 20 30]


In [245]:
b=np.tile(a,[2,3])#对a进行扩展，扩展为：行为原来2倍，宽为原来3倍
print(b)

[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [ ]:
#排序

In [248]:
a=np.array([[4,3,5],[1,2,1]])
a

array([[4, 3, 5],
       [1, 2, 1]])

In [251]:
b=np.sort(a,axis=1)#将数组a进行每行排序
b

array([[3, 4, 5],
       [1, 1, 2]])

In [256]:
c=np.array([4,3,1,2])
c

array([4, 3, 1, 2])

In [257]:
d=np.argsort(c)#argsort求的是索引，从小到大排序，输出对应数值的位置
d

array([2, 3, 1, 0])

In [ ]:
#将索引传入数组中，传出对应数值

In [258]:
print(c[d])

[1 2 3 4]
